-- ZolTrack v8.8 - Persistent Notifications + Audit Log
-- Run once AFTER v8.7. Does not delete or rewrite operational history.
begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  message text not null,
  entity_type text,
  entity_id text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_recipient_created_idx on public.notifications(recipient_id, created_at desc);
create index if not exists notifications_recipient_unread_idx on public.notifications(recipient_id, is_read) where is_read=false;
alter table public.notifications enable row level security;
drop policy if exists "v88 notification owner read" on public.notifications;
drop policy if exists "v88 notification owner update" on public.notifications;
create policy "v88 notification owner read" on public.notifications for select to authenticated using (recipient_id=auth.uid());
create policy "v88 notification owner update" on public.notifications for update to authenticated using (recipient_id=auth.uid()) with check (recipient_id=auth.uid());
revoke insert, delete on public.notifications from authenticated;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_name text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_log_created_idx on public.audit_log(created_at desc);
create index if not exists audit_log_entity_idx on public.audit_log(entity_type, entity_id);
alter table public.audit_log enable row level security;
drop policy if exists "v88 superadmin audit read" on public.audit_log;
create policy "v88 superadmin audit read" on public.audit_log for select to authenticated using (public.current_user_role()='superadmin');
revoke insert, update, delete on public.audit_log from authenticated;

create or replace function public.v88_actor_name(p_uid uuid) returns text
language sql security definer stable set search_path=public as $$
  select coalesce((select full_name from public.profiles where id=p_uid), 'System');
$$;
revoke all on function public.v88_actor_name(uuid) from public, anon, authenticated;

create or replace function public.v88_notify(p_recipient uuid,p_type text,p_title text,p_message text,p_entity_type text default null,p_entity_id text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_recipient is not null then
    insert into public.notifications(recipient_id,type,title,message,entity_type,entity_id)
    values(p_recipient,coalesce(p_type,'system'),p_title,p_message,p_entity_type,p_entity_id);
  end if;
end $$;
revoke all on function public.v88_notify(uuid,text,text,text,text,text) from public, anon, authenticated;

create or replace function public.v88_audit(p_action text,p_entity_type text,p_entity_id text,p_summary text,p_details jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();
begin
  insert into public.audit_log(actor_id,actor_name,action,entity_type,entity_id,summary,details)
  values(v_uid,public.v88_actor_name(v_uid),p_action,p_entity_type,p_entity_id,p_summary,coalesce(p_details,'{}'::jsonb));
end $$;
revoke all on function public.v88_audit(text,text,text,text,jsonb) from public, anon, authenticated;

create or replace function public.v88_maintenance_events() returns trigger
language plpgsql security definer set search_path=public as $$
declare r record; rid text:=new.request_id::text;
begin
  if tg_op='INSERT' then
    perform public.v88_audit('created','maintenance',rid,'Maintenance request submitted',jsonb_build_object('status',new.status,'priority',new.priority));
    for r in select id from public.profiles where approved=true and coalesce(active,true)=true and role in ('admin','superadmin') loop
      if r.id is distinct from new.submitted_by_auth then perform public.v88_notify(r.id,'maintenance','New maintenance request',rid||' is waiting for review.','maintenance',rid); end if;
    end loop;
  elsif tg_op='UPDATE' then
    if new.status is distinct from old.status then
      perform public.v88_audit('status_changed','maintenance',rid,'Maintenance status changed from '||coalesce(old.status,'—')||' to '||coalesce(new.status,'—'),jsonb_build_object('from',old.status,'to',new.status));
      perform public.v88_notify(new.submitted_by_auth,'maintenance','Maintenance request updated',rid||' is now '||coalesce(new.status,'updated')||'.','maintenance',rid);
    end if;
    if new.assigned_to_auth is distinct from old.assigned_to_auth and new.assigned_to_auth is not null then
      perform public.v88_audit('assigned','maintenance',rid,'Maintenance request assigned',jsonb_build_object('assigned_to',new.assigned_to_auth));
      perform public.v88_notify(new.assigned_to_auth,'maintenance','Maintenance assignment','You were assigned to '||rid||'.','maintenance',rid);
    end if;
    if coalesce(new.deduct_inventory,false)=true and coalesce(old.deduct_inventory,false)=false then
      perform public.v88_audit('inventory_deducted','maintenance',rid,'Inventory deducted during maintenance completion',jsonb_build_object('item_id',new.deducted_inventory_item_id,'quantity',new.deducted_inventory_quantity));
    end if;
  end if;
  return new;
end $$;
drop trigger if exists v88_maintenance_events on public.maintenance_requests;
create trigger v88_maintenance_events after insert or update on public.maintenance_requests for each row execute function public.v88_maintenance_events();

create or replace function public.v88_borrow_events() returns trigger
language plpgsql security definer set search_path=public as $$
declare r record; bid text:=new.id::text;
begin
  if tg_op='INSERT' then
    perform public.v88_audit('created','borrow',bid,'Borrow request submitted',jsonb_build_object('item_id',new.item_id,'quantity',new.quantity,'status',new.status));
    for r in select id from public.profiles where approved=true and coalesce(active,true)=true and role in ('admin','superadmin') loop
      if r.id is distinct from new.borrower_auth then perform public.v88_notify(r.id,'borrow','New borrow request',coalesce(new.borrower_name,'A user')||' submitted a borrow request.','borrow',bid); end if;
    end loop;
  elsif new.status is distinct from old.status then
    perform public.v88_audit('status_changed','borrow',bid,'Borrow status changed from '||coalesce(old.status,'—')||' to '||coalesce(new.status,'—'),jsonb_build_object('from',old.status,'to',new.status,'item_id',new.item_id));
    perform public.v88_notify(new.borrower_auth,'borrow','Borrow request updated','Your borrow request is now '||coalesce(new.status,'updated')||'.','borrow',bid);
  end if;
  return new;
end $$;
drop trigger if exists v88_borrow_events on public.borrow_transactions;
create trigger v88_borrow_events after insert or update on public.borrow_transactions for each row execute function public.v88_borrow_events();

create or replace function public.v88_profile_events() returns trigger
language plpgsql security definer set search_path=public as $$
declare r record; pid text:=new.id::text;
begin
  if new.verification_document is distinct from old.verification_document and new.verification_document is not null then
    perform public.v88_audit('verification_submitted','profile',pid,'Verification document submitted');
    for r in select id from public.profiles where approved=true and coalesce(active,true)=true and role='superadmin' loop
      if r.id is distinct from new.id then perform public.v88_notify(r.id,'approval','Verification submitted',coalesce(new.full_name,'A user')||' is waiting for account review.','profile',pid); end if;
    end loop;
  end if;
  if new.approved is distinct from old.approved then
    perform public.v88_audit(case when new.approved then 'approved' else 'approval_changed' end,'profile',pid,case when new.approved then 'Account approved' else 'Account approval removed' end);
    perform public.v88_notify(new.id,'account',case when new.approved then 'Account approved' else 'Account status updated' end,case when new.approved then 'Your ZolTrack account has been approved.' else coalesce('Your account requires attention. '||nullif(new.rejection_reason,''),'Your account approval status changed.') end,'profile',pid);
  elsif new.rejection_reason is distinct from old.rejection_reason and new.rejection_reason is not null then
    perform public.v88_audit('rejected','profile',pid,'Account verification rejected');
    perform public.v88_notify(new.id,'account','Verification rejected','Your verification was rejected. '||new.rejection_reason,'profile',pid);
  end if;
  if new.role is distinct from old.role then
    perform public.v88_audit('role_changed','profile',pid,'User role changed from '||old.role||' to '||new.role,jsonb_build_object('from',old.role,'to',new.role));
    perform public.v88_notify(new.id,'account','Role updated','Your role is now '||new.role||'.','profile',pid);
  end if;
  if new.active is distinct from old.active then
    perform public.v88_audit('account_status_changed','profile',pid,'Account active status changed',jsonb_build_object('active',new.active));
    perform public.v88_notify(new.id,'account','Account status updated',case when new.active then 'Your account has been activated.' else 'Your account has been deactivated.' end,'profile',pid);
  end if;
  return new;
end $$;
drop trigger if exists v88_profile_events on public.profiles;
create trigger v88_profile_events after update on public.profiles for each row execute function public.v88_profile_events();

-- Safe RPCs used by the frontend. RLS still scopes notification rows to auth.uid().
create or replace function public.get_notifications_v88(p_limit integer default 30)
returns table(id bigint,type text,title text,message text,entity_type text,entity_id text,is_read boolean,created_at timestamptz)
language sql security invoker set search_path=public as $$
 select n.id,n.type,n.title,n.message,n.entity_type,n.entity_id,n.is_read,n.created_at
 from public.notifications n where n.recipient_id=auth.uid()
 order by n.created_at desc limit least(greatest(coalesce(p_limit,30),1),100);
$$;
create or replace function public.mark_notifications_read_v88()
returns integer language plpgsql security invoker set search_path=public as $$
declare c integer; begin update public.notifications set is_read=true where recipient_id=auth.uid() and is_read=false; get diagnostics c=row_count; return c; end $$;
create or replace function public.get_audit_log_v88(p_limit integer default 100)
returns table(id bigint,actor_name text,action text,entity_type text,entity_id text,summary text,details jsonb,created_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
 if public.current_user_role()<>'superadmin' then raise exception 'Super Admin access required'; end if;
 return query select a.id,a.actor_name,a.action,a.entity_type,a.entity_id,a.summary,a.details,a.created_at from public.audit_log a order by a.created_at desc limit least(greatest(coalesce(p_limit,100),1),250);
end $$;
revoke all on function public.get_notifications_v88(integer) from public;
revoke all on function public.mark_notifications_read_v88() from public;
revoke all on function public.get_audit_log_v88(integer) from public;
grant execute on function public.get_notifications_v88(integer) to authenticated;
grant execute on function public.mark_notifications_read_v88() to authenticated;
grant execute on function public.get_audit_log_v88(integer) to authenticated;

commit;

-- Verification
select table_name from information_schema.tables where table_schema='public' and table_name in ('notifications','audit_log') order by table_name;
select trigger_name,event_object_table from information_schema.triggers where trigger_schema='public' and trigger_name like 'v88_%' order by trigger_name;
